/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultorSlugRouteImport } from './routes/consultor.$slug'
import { Route as MatrixSlugRouteImport } from './routes/matrix.$slug'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorSlugRoute = ConsultorSlugRouteImport.update({
  id: '/consultor/$slug',
  path: '/consultor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixSlugRoute = MatrixSlugRouteImport.update({
  id: '/matrix/$slug',
  path: '/matrix/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/matrix': typeof MatrixRoute
  '/consultor/$slug': typeof ConsultorSlugRoute
  '/matrix/$slug': typeof MatrixSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/matrix': typeof MatrixRoute
  '/consultor/$slug': typeof ConsultorSlugRoute
  '/matrix/$slug': typeof MatrixSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/admin': typeof AdminRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRoute
  '/matrix': typeof MatrixRoute
  '/consultor/$slug': typeof ConsultorSlugRoute
  '/matrix/$slug': typeof MatrixSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/matrix'
    | '/consultor/$slug'
    | '/matrix/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/matrix'
    | '/consultor/$slug'
    | '/matrix/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/admin'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/matrix'
    | '/consultor/$slug'
    | '/matrix/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AdminRoute: typeof AdminRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRoute
  MatrixRoute: typeof MatrixRoute
  ConsultorSlugRoute: typeof ConsultorSlugRoute
  MatrixSlugRoute: typeof MatrixSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor/$slug': {
      id: '/consultor/$slug'
      path: '/consultor/$slug'
      fullPath: '/consultor/$slug'
      preLoaderRoute: typeof ConsultorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix/$slug': {
      id: '/matrix/$slug'
      path: '/matrix/$slug'
      fullPath: '/matrix/$slug'
      preLoaderRoute: typeof MatrixSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AdminRoute: AdminRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRoute,
  MatrixRoute: MatrixRoute,
  ConsultorSlugRoute: ConsultorSlugRoute,
  MatrixSlugRoute: MatrixSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
